league/urls.py
from django.conf.urls import url
from django.contrib import admin
from league_tracker import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^add_user/', views.create_user),
    url(r'^add_deck/', views.create_deck),
    url(r'^add_record/', views.create_record),
    url(r'^add_event/', views.create_event),
    url(r'^update_record/(?P<id>\d+)/$', views.update_record),
    url(r'^delete_record/(?P<id>\d+)/$', views.delete_record),
    url(r'^records/(?P<id>\d+)/$', views.records),
    url(r'^records/$', views.all_records),
    url(r'^statistics/$', views.statistics),
    url(r'^$', views.index),
]

league_tracker/models.py
from django.db import models
from django.utils.functional import cached_property
from django.template.defaultfilters import slugify
import requests

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250)
    is_bye = models.BooleanField(default=False)
    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.name

class Decks(models.Model):
    deck_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True) 
    game = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    runner_id = models.CharField(max_length=250, null=True)
    runner_faction = models.CharField(max_length=250, null=True)
    corp_id = models.CharField(max_length=250, null=True)
    corp_faction = models.CharField(max_length=250, null=True)
    class Meta:
        unique_together = ('user_id', 'game')

class StatsManager(models.Manager):
    def sos(self, user_id, event_id=None): 
        if not event_id:
            own_records = self.filter(user_id_id=user_id)
            opponents = [rec.opponent_id_id for rec in own_records if rec.opponent_id_id!=1]
            opponents_records = self.filter(user_id_id__in=opponents)
        else:
            own_records = self.filter(user_id_id=user_id).filter(game_id=event_id)
            opponents = [rec.opponent_id_id for rec in own_records if rec.opponent_id_id!=1]
            opponents_records = self.filter(user_id_id__in=opponents).filter(game_id=event_id)
        denom = 0
        num = 0
        for opponent in opponents: 
            runner_results = list(opponents_records.filter(user_id_id=opponent).values_list('runner_status', flat=True))
            corp_results = list(opponents_records.filter(user_id_id=opponent).values_list('corp_status', flat=True))
            points = 0
            for result in [runner_results, corp_results]:
                points += sum([3 for item in result if item == 'WI']) 
                points += sum([2 for item in result if item == 'TW'])
                points += sum([1 for item in result if item == 'TI'])
            if len(runner_results) == 0:
                points /= 1
            else:
                points /= len(runner_results)
            denom += points
            num += 1
        if num == 0:
            return 0
        else:
            return denom/num

    def esos(self, user_id, event_id=None):
        own_records = self.filter(user_id_id=user_id)
        opponents = [rec.opponent_id_id for rec in own_records if rec.opponent_id_id!=1]
        opp_sos = [self.sos(opp) for opp in opponents]
        if len(opp_sos) == 0:
            return 0
        else:
            return sum(opp_sos)/len(opp_sos)

    def total_games(self, user_id, event_id=None):
        own_records = self.filter(user_id_id=user_id).count()
        return own_records

    
    def total_points(self, user_id):
        own_records = self.filter(user_id_id=user_id)
        runner_results = list(own_records.values_list('runner_status', flat=True))
        corp_results = list(own_records.values_list('corp_status', flat=True))
        points = 0
        for result in [runner_results, corp_results]:
            points += sum([3 for item in result if item == 'WI']) 
            points += sum([2 for item in result if item == 'TW'])
            points += sum([1 for item in result if item == 'TI'])
        return points

class Records(models.Model):
    WIN_LOSE = (
            ('WI', 'Win'),
            ('TW', 'Timed Win'),
            ('TL', 'Timed Loss'),
            ('LO', 'Lose'),
            ('TI', 'Tie'),
            )
    choices = [(i, i) for i in range(1, 16)]
    user_id = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE)
    opponent_id = models.ForeignKey(User, related_name='+', on_delete=models.CASCADE)
    corp_status = models.CharField(max_length=2, choices=WIN_LOSE, null=True, default='WI')
    runner_status = models.CharField(max_length=2, choices=WIN_LOSE, null=True, default='WI')
    game = models.ForeignKey(Event, related_name='+', null=True, blank=True, on_delete=models.CASCADE)
    round_num = models.IntegerField(null=True, default=1, choices=choices)
    display = models.BooleanField(default=True)
    linked_record = models.IntegerField(null=True, default=1)
    objects = models.Manager()
    stats = StatsManager()

league_tracker/forms.py
from django import forms
from django.core.exceptions import ValidationError
from league_tracker.models import User, Decks, Records, Event
import requests

def get_faction_dictionary():
    r = requests.get('https://netrunnerdb.com/api/2.0/public/cards')
    payload = r.json()['data']
    runner_vals = {}
    corp_vals = {}
    for card in payload:
        if card['type_code'] == 'identity':
            if card['side_code'] == 'corp':
                corp_vals[card['title']] = card['faction_code']
            else:
                runner_vals[card['title']] = card['faction_code']
    return runner_vals, corp_vals

class UserForm(forms.ModelForm):
   class Meta:
       model = User
       fields = ['name']

class DeckForm(forms.ModelForm):
    runner_vals, corp_vals = get_faction_dictionary()
    runner_choices = [(x, x) for x in sorted(runner_vals.keys())]
    corp_choices = [(x, x) for x in sorted(corp_vals.keys())]
    runner_id = forms.ChoiceField(choices=runner_choices)
    corp_id = forms.ChoiceField(choices=corp_choices)
    class Meta:
        model = Decks
        fields = ['user_id', 'game', 'runner_id', 'corp_id']

class RecordForm(forms.ModelForm):
    user_id = forms.ModelChoiceField(queryset=User.objects, empty_label=None)
    opponent_id = forms.ModelChoiceField(queryset=User.objects, empty_label=None)
    game = forms.ModelChoiceField(queryset=Event.objects.order_by('-date'), empty_label=None)
    class Meta:
        model = Records
        fields = ['user_id', 'opponent_id', 'corp_status',
                'runner_status', 'game', 'round_num']

class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

league_tracker/views.py
from django.db.models import Count, Max, F
from django.shortcuts import render, get_object_or_404
from league_tracker.models import User, Records, Decks, Event
from league_tracker.forms import UserForm, DeckForm, RecordForm, EventForm, get_faction_dictionary 
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def index(request): 
    return render(request, 'index.html')

def create_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        form.save()
        return HttpResponseRedirect('/')
    else:
        form = UserForm()
    return render(request, 'add_user.html', {'form': form})

def create_deck(request):
    if request.method == 'POST':
        runner_vals, corp_vals = get_faction_dictionary()
        payload = request.POST.copy()
        form = DeckForm(payload)
        form.save()
        updater = Decks.objects.last()
        updater.runner_faction = runner_vals[payload['runner_id']]
        updater.corp_faction = corp_vals[payload['corp_id']]
        updater.save()
        return HttpResponseRedirect('/')
    else:
        form = DeckForm()
    return render(request, 'add_decks.html', {'form': form})

def create_record(request):
    ### When somebody puts in a result we want to put in  reverse as well
    ### for example: user 3 sweeps user 1, we want to include a result for
    ### user 3 - user 1 6-0 points
    ### user 1 - user 3 0-6 points
    if request.method == 'POST':
        form = RecordForm(request.POST)
        reverse_form = request.POST.copy()
        original_form = request.POST.copy()
        form.save()
        reverse_form['opponent_id'] = request.POST['user_id']
        reverse_form['user_id'] = request.POST['opponent_id']
        flip_dict = {
                'WI': 'LO',
                'LO': 'WI',
                'TW': 'TL',
                'TL': 'TW',
                'TI': 'TI',
                }
        for stat in ['runner_status', 'corp_status']:
            reverse_form[stat] = flip_dict[request.POST[stat]]
        form = RecordForm(reverse_form)
        form.save()
        opp_record = Records.objects.last()
        opp_record.linked_record = opp_record.pk - 1
        opp_record.display = False
        opp_record.save()
        user_record = Records.objects.get(pk=opp_record.pk-1)
        user_record.linked_record = user_record.pk + 1
        user_record.save()
        return HttpResponseRedirect('/')
    else:
        form = RecordForm()
    return render(request, 'add_records.html', {'form': form})

def update_record(request, id):
    record = Records.objects.get(pk=id)
    form = RecordForm(request.POST or None, instance=record)
    if request.method == 'POST':
        form.save()
        linked_record = Records.objects.get(pk=record.linked_record)
        updated_record = Records.objects.get(pk=id)
        linked_record.user_id = updated_record.opponent_id
        linked_record.opponent_id = updated_record.user_id
        linked_record.game = updated_record.game
        linked_record.round_num = updated_record.round_num
        flip_dict = {
                'WI': 'LO',
                'LO': 'WI',
                'TW': 'TL',
                'TL': 'TW',
                'TI': 'TI',
                }
        linked_record.runner_status = flip_dict[updated_record.runner_status]
        linked_record.corp_status = flip_dict[updated_record.corp_status]
        linked_record.save()
        return HttpResponseRedirect('/')
    return render(request, 'update_records.html', {'form': form, 'id': id})

def delete_record(request, id):
    record = Records.objects.filter(id=id)
    partner = record[0].linked_record
    Records.objects.filter(id=id).delete()
    Records.objects.filter(id=partner).delete()
    return HttpResponseRedirect('/')
    

def create_event(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        form.save()
        return HttpResponseRedirect('/')
    else:
        form = EventForm()
    return render(request, 'add_event.html', {'form': form})


def return_all_standings(request):
    all_records = Records.objects.all()
    context = {
            'record': all_record,
            }
    return render(request, 'index.html', context)

def records(request, id):
    records = Records.objects.filter(user_id_id=id).order_by('-game', 'round_num')
    sos = Records.stats.sos(id)
    esos = Records.stats.esos(id)
    user = User.objects.get(pk=id)
    decks = Decks.objects.filter(user_id_id=id).order_by('-game')
    context = {
            'records': records,
            'user': user,
            'sos': sos,
            'esos': esos,
            'deck': decks,
            }
    return render(request, 'standings.html', context)

point_vals = {
            'WI': 3,
            'TW': 2,
            'TI': 1,
            'TL': 0,
            'LO': 0
            }

def faction_records(records, decks):    
    vals = {}
    for record in records:
        game_deck = decks.filter(user_id=record.user_id_id, game=record.game_id).first()
        if game_deck is not None:
            if game_deck.corp_faction not in vals.keys():
                vals[game_deck.corp_faction] = {}
                vals[game_deck.corp_faction]['points'] = point_vals[record.corp_status]
                vals[game_deck.corp_faction]['num_rounds'] = 1
            else:
                vals[game_deck.corp_faction]['points'] += point_vals[record.corp_status]
                vals[game_deck.corp_faction]['num_rounds'] += 1
            if game_deck.runner_faction not in vals.keys():
                vals[game_deck.runner_faction] = {}
                vals[game_deck.runner_faction]['points'] = point_vals[record.runner_status]
                vals[game_deck.runner_faction]['num_rounds'] = 1
            else:
                vals[game_deck.runner_faction]['points'] += point_vals[record.runner_status]
                vals[game_deck.runner_faction]['num_rounds'] +=1
    return vals

def id_records(records, decks):
    vals = {}
    for record in records:
        game_deck = decks.filter(user_id=record.user_id_id, game=record.game_id).first()
        if game_deck is not None:
            if game_deck.corp_id not in vals.keys():
                vals[game_deck.corp_id] = {}
                vals[game_deck.corp_id]['points'] = point_vals[record.corp_status]
                vals[game_deck.corp_id]['num_rounds'] = 1
            else:
                vals[game_deck.corp_id]['points'] += point_vals[record.corp_status]
                vals[game_deck.corp_id]['num_rounds'] += 1
            if game_deck.runner_id not in vals.keys():
                vals[game_deck.runner_id] = {}
                vals[game_deck.runner_id]['points'] = point_vals[record.runner_status]
                vals[game_deck.runner_id]['num_rounds'] = 1
            else:
                vals[game_deck.runner_id]['points'] += point_vals[record.runner_status]
                vals[game_deck.runner_id]['num_rounds'] += 1
    return vals

def all_records(request, game_night=None):
    records = Records.objects.all().filter(display=True)
    all_players = set(list(Records.objects.values_list('user_id_id', flat=True)))
    all_players = [player for player in all_players if player!=1]
    stats = {}
    for player in all_players:
        decks = Decks.objects.filter(user_id=player)
        corp_factions = decks.distinct('corp_faction').values('corp_faction')
        runner_factions = decks.distinct('runner_faction').values('runner_faction')
        points = Records.stats.total_points(player)
        total_possible = Records.stats.total_games(player) * 6 # because there's a max value of 6 points in each round
        point_percentage = (points / total_possible ) * 100
        stats[player] = {
                'name': User.objects.filter(user_id=player).values('name')[0]['name'],
                'total_games': Records.stats.total_games(player),
                'points': points,
                'point_percentage': point_percentage,
                'runner_factions': ', '.join([faction['runner_faction'].title() for faction in runner_factions]),
                'corp_factions': ', '.join([faction['corp_faction'].title() for faction in corp_factions]),
                'sos': Records.stats.sos(player),
                'esos': Records.stats.esos(player),
                }
    context = {
            'records': records,
            'stats': stats,
            }
    return render(request, 'records.html', context)

def statistics(request):
    non_filtered_records = Records.objects.exclude(user_id_id=1)
    all_decks = Decks.objects.all()
    faction_recs = faction_records(non_filtered_records, all_decks)
    id_recs = id_records(non_filtered_records, all_decks)
    runner_records = non_filtered_records.values('runner_status').annotate(runner_count=Count('runner_status')).order_by('-runner_status')
    corp_records = non_filtered_records.values('corp_status').annotate(corp_count=Count('corp_status')).order_by('-corp_status')
    runner = [record for record in runner_records]
    corp = [record for record in corp_records]
    win_rates = {}
    for x in range(len(runner)):
        newkey = runner[x]['runner_status']
        win_rates[newkey] = {
                'runner': runner[x].get('runner_count', 0),
                'corp': corp[x].get('corp_count', 0),
                }
    for key in ['WI', 'LO', 'TW', 'TL', 'TI']:
        if not win_rates.get(key, None):
            win_rates[key] = {
                    'runner': 0,
                    'corp': 0
                    }
    ordered_id_rates = []
    for key in sorted(id_recs, key=lambda x: (id_recs[x]['points']),reverse=True):
        win_rate = (id_recs[key]['points'] / (id_recs[key]['num_rounds'] * 3)) *100
        ordered_id_rates.append((key.title(), id_recs[key]['points'], id_recs[key]['num_rounds'], win_rate))
    ordered_faction_rates = []

league_tracker/templates/add_decks.html
{% extends 'base.html' %}
{% block content %}
<p> this exists? but for decks</p>

<form action="/add_deck/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value ="Submit" />
</form> 
{% endblock %}

league_tracker/templates/add_event.html
{% extends 'base.html' %}
{% block content %}
<p> this exists? </p>

<form action="/add_event/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value ="Submit" />
</form> 
{% endblock %}

league_tracker/templates/add_league.html
{% extends 'base.html' %}
{% block content %}
<p> this exists? but for leagues</p>

<form action="/add_league/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value ="Submit" />
</form> 
{% endblock %}

league_tracker/templates/add_records.html
{% extends 'base.html' %}
{% block content %}
<p> this exists? but for records?</p>

<form action="/add_record/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value ="Submit" />
</form> 
{% endblock %}

league_tracker/templates/add_user.html
{% extends 'base.html' %}
{% block content %}
<p> this exists? </p>

<form action="/add_user/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value ="Submit" />
</form> 
{% endblock %}

league_tracker/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Chicago League Tracker</title>
        {% load staticfiles %}
        <link rel ="shortcut icon" href="{% static 'favicon/favicon.ico' %}"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    </head>
    <body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">League Manager</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="/records/">Current Standings</a></li>
	        <li><a href="/statistics/">Statistics</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="/add_user/">Player</a></li>
	            <li><a href="/add_event/">Event</a></li>
	            <li><a href="/add_deck/">Deck</a></li>
	            <li><a href="/add_record/">Match</a></li>
	          </ul>
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
	<div class="container">
		<div class="starter-template">
	        {% block content %}
	        {% endblock %}
	    </div>
	</div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </body>
</html>

league_tracker/templates/index.html
{% extends 'base.html' %}
{% block content %}

<h1>League Tracker</h1>

<p>This website is still very much under construction, but should be good enough to use for the time being.</p>

<p>And hey, now it is online!

<p>I keep editing this file just to make sure migrations work</p>

{% endblock %}

league_tracker/templates/records.html
{% extends 'base.html' %}
{% load extras %}
{% block content %}

<h3 class="text-center">Player Standings</h3>

<table class="table table-condensed">
    <tr>
        <th>Player Name</th>
        <th class="text-center">Total Number of Rounds Played</th>
        <th class="text-center">Total Points</th>
        <th class="text-center">Point Percentage</th>
        <th class="text-center">Runner Factions</th>
        <th class="text-center">Corp Factions</th>
        <th class="text-center">Strength of Schedule</th>
        <th class="text-center">Extended Strength of Schedule</th>
    </tr>

{% for key, value in stats.items|dictsortreversed:"1.sos"|dictsortreversed:"1.points" %}
<tr>
    <td><a href="/records/{{ key }}">{{ value.name }}</a></td> 
    <td class="text-center">{{ value.total_games }}</td> 
    <td class="text-center">{{ value.points }}</td>
    <td class="text-center">{{ value.point_percentage|floatformat:"2" }}%</td>
    <td class="text-center">{{ value.runner_factions }}</td>
    <td class="text-center">{{ value.corp_factions }}</td>
    <td class="text-center">{{ value.sos|floatformat:"2" }}</td> 
    <td class="text-center">{{ value.esos|floatformat:"2" }}</td>
</tr>
{% endfor %}
</table>

<h3 class="text-center">Match History</h3>

<table class="table table-condensed">
    <tr class="text-center">
        <th>Player</th>
        <th>Opponent</th>
        <th class="text-center">As Runner</th>
        <th class="text-center">As Corporation</th>
        <th></th>
        <th></th>
    </tr>

{% for record in records %}
{% endfor %}

{% regroup records|dictsortreversed:"game_id" by game as game_list %}
{% for game in game_list %}
<tr>
    <td colspan="6" class="success text-center">{{ game.grouper }}</td>
</tr>
{% regroup game.list|dictsortreversed:"round_num" by round_num as round_list %}
{% for round in round_list %}
<tr>
    <td colspan="6" class="info text-center">Round {{ round.grouper }}</td>
</tr>
{% for item in round.list %}
<tr>
    <td><a href="/records/{{ item.user_id_id }}">{{ item.user_id.name }}</a></td>
    <td><a href="/records/{{ item.opponent_id_id }}">{{ item.opponent_id.name }}</a></td>
    <td class="text-center">{{ item.get_runner_status_display }}</td>
    <td class="text-center">{{ item.get_corp_status_display }}</td>
    <td class="text-center"><a href="/update_record/{{ item.id }}/">Update</a></td>
    <td class="text-center"><a href="/delete_record/{{ item.id }}/">Delete</a></td>
</tr>
{% endfor %}
{% endfor %}
{% endfor %}
</table>

{% endblock %}

league_tracker/templates/standings.html
{% extends 'base.html' %}
{% block content %}

<h4 class="text-center">{{ user.name }}</h4> 
<p class="text-center"><i>Strength of Schedule: {{ sos|floatformat:"2" }}, Extended Strength of Schedule: {{ esos|floatformat:"2" }}</i></p>

<table class="table table-condensed">
    <tr>
        <th>Opponent</th>
        <th class="text-center">Corporation</th>
        <th class="text-center">Runner</th>
        <th class="text-center">Game Night</th>
        <th class="text-center">Round Number</th>
    </tr>
{% for rec in records %}
<tr>
    <td><a href="/records/{{ rec.opponent_id_id }}"> {{ rec.opponent_id}}</a></td>
    <td class="text-center"> {{ rec.get_corp_status_display }}</td>
    <td class="text-center"> {{ rec.get_runner_status_display }}</td>
    <td class="text-center"> {{ rec.game }}</td>
    <td class="text-center"> {{ rec.round_num }}</td>
</tr>
{% endfor %}

<table class="table table-condensed">
    <tr>
        <th>Event</th>
        <th class="text-center">Runner ID</th>
        <th class="text-center">Corporation ID</th>
    </tr>
{% for d in deck %}
    <tr>
        <td>{{ d.game }}</td>
        <td class="text-center">{{ d.runner_id }}</td>
        <td class="text-center">{{ d.corp_id }}</td>
    </tr>
{% endfor %}
</table>

{% endblock %}

league_tracker/templates/statistics.html
{% extends 'base.html' %}
{% block content %}

<!---
<h3 class="text-center">Wins by Side</h3>

<table class="table table-condensed">
    <tr>
        <th> </th>
        <th>Runner</th>
        <th>Corporation</th>
    </tr>
    <tr>
        <td>Round Wins</td>
        <td>{{ win_rates.WI.runner }}</td>
        <td>{{ win_rates.WI.corp }}</td>
    </tr>
    <tr>
        <td>Round Timed Wins</td>
        <td>{{ win_rates.TW.runner }}</td>
        <td>{{ win_rates.TW.corp }}</td>
    </tr>
    <tr>
        <td>Round Ties</td>
        <td>{{ win_rates.TI.runner }}</td>
        <td>{{ win_rates.TI.corp }}</td>
    </tr>
</table>
-->

<h3 class="text-center">Points by Faction</h3>

<table class="table table-condensed">
    <tr>
        <th>Faction</th>
        <th class="text-center">Points</th>
        <th class="text-center">Number of Rounds Played</th>
        <th class="text-center">Win Rate</th>
    </tr>
    {% for item in faction_records %}
    <tr>
        <td>{{ item.0 }}</td>
        <td class="text-center">{{ item.1 }}</td>
        <td class="text-center">{{ item.2 }}</td>
        <td class="text-center">{{ item.3|floatformat:"2" }}%</td>
    </tr>
    {% endfor %}
</table>

<h3 class="text-center">Points by Identity</h3>

<table class="table table-condensed">
    <tr>
        <th>ID</th>
        <th class="text-center">Points</th>
        <th class="text-center">Number of Rounds Played</th>
        <th class="text-center">Win Rate</th>
    </tr>
    {% for item in id_records %}
    <tr>
        <td>{{ item.0 }}</td>
        <td class="text-center">{{ item.1 }}</td>
        <td class="text-center">{{ item.2 }}</td>
        <td class="text-center">{{ item.3|floatformat:"2" }}%</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

league_tracker/templates/update_records.html
{% extends 'base.html' %}
{% block content %}
<p> this exists? but for records?</p>

<form action="/update_record/{{ id }}/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value ="Submit" />
</form> 
{% endblock %}